name: RL_HW3
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - swig
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.8
  - pip:
      - box2d-py==2.3.5
      - cloudpickle==3.1.0
      - gymnasium==1.0.0
      - matplotlib==3.10.0
      - opencv-python==4.10.0.84
      - pygame==2.6.1
      - tqdm==4.67.1